### ISSUE TITLE
[Request] Multi-screen/monitor

### ISSUE THREAD

**Issue by fsmythe** [pkillboredom/ElDewritoSimpleSplitScreen#2]
Great job so far!

Long shot, but is there any chance of getting multi-screen/monitor support down the line?

Cheers

**Comment by pkillboredom** [comment]
Technically there already is. Let's say you had two 1080p screens next to each other. If they are both aligned in display settings to have their corners lined up, you just need to set a game position at X: 1920, Y:0. Windows should be treating this as one huge canvas, with 0-1919 being monitor one, and 1920-3839 being monitor two. Good idea though, I'll make this easier down the line.


On Apr 22, 2018 at 12:00 PM, <teenspirit7<mailto:notifications@github.com>> wrote:


Great job so far!

Long shot, but is there any chance of getting multi-screen/monitor support down the line?

Cheers

**Comment by fsmythe** [comment]
Wow,

That does indeed work! Requires some maths as I've got 4 monitors running different resolutions.

Great,

Thanks!
