### ISSUE TITLE
Confussed. The download does not contain ED06Splitter.exe?

### ISSUE THREAD

**Issue by TannerLevi** [pkillboredom/ElDewritoSimpleSplitScreen#4]
The download does not contain ED06Splitter.exe that was mentioned in the readme
I may just be stupid and clueless but any help would be great. I usually can figure most things out.
Thanks in advanced!

**Comment by twist84** [comment]
Are you sure?
[/releases/download/v1.0.0/ED06Splitter.zip](https://github.com/pkillboredom/ElDewritoSimpleSplitScreen/releases/download/v1.0.0/ED06Splitter.zip)
![image](https://user-images.githubusercontent.com/6237734/59456367-12f14980-8e0e-11e9-9c3e-6aaebb93d413.png)
